server:
  port: 4001
  assets-path: /app/assets
  proxied: true
  base-url: /

auth:
  secret-key: KEY
  users:
    odyw:
      password-hash: HASH

theme:
  # custom-css-file: /assets/user.css
  background-color: 50 1 6
  primary-color: 24 97 58
  negative-color: 209 88 54

pages:
  # - $include: home.yml
